# Generated by Django 6.0.4 on 2026-05-05 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_applicationconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationconfig',
            name='properties',
            field=models.JSONField(default=dict),
        ),
    ]
