# Generated by Django 6.0.4 on 2026-05-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_applicationconfig_properties'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
