# Generated by Django 6.0.4 on 2026-05-16 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('debate', '0004_category_icon_topic_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('pro_content', models.TextField()),
                ('con_content', models.TextField()),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debate.topic')),
            ],
        ),
    ]
