# Generated by Django 6.0.4 on 2026-05-16 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perspective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True)),
                ('context_2line', models.TextField(blank=True)),
                ('view_1_label', models.CharField(blank=True, max_length=64)),
                ('view_1_text', models.TextField(blank=True)),
                ('view_2_label', models.CharField(blank=True, max_length=64)),
                ('view_2_text', models.TextField(blank=True)),
                ('debatable', models.BooleanField()),
                ('drop_reason', models.TextField(blank=True)),
                ('source_event_url', models.URLField(max_length=1024)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('dropped', 'Dropped')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
