# Generated by Django 6.0.4 on 2026-05-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_perspective'),
    ]

    operations = [
        migrations.AddField(
            model_name='perspective',
            name='event_context',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='perspective',
            name='event_date',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='perspective',
            name='event_source',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='perspective',
            name='event_title',
            field=models.TextField(blank=True),
        ),
    ]
