# Generated by Django 6.0.4 on 2026-05-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_perspective_event_context_perspective_event_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perspective',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=1024),
        ),
    ]
