# Generated by Django 6.0.4 on 2026-04-25 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Debate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('MATCHED', 'Matched'), ('ONGOING', 'Ongoing'), ('JUDGING', 'Judging'), ('COMPLETED', 'Completed'), ('DISPUTED', 'Disputed'), ('ABANDONED', 'Abandoned')], max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user_con', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='con_debates', to=settings.AUTH_USER_MODEL)),
                ('user_pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pro_debates', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_debates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Judgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('argument_score_pro', models.FloatField()),
                ('rebuttal_score_pro', models.FloatField()),
                ('clarity_score_pro', models.FloatField()),
                ('persuasion_score_pro', models.FloatField()),
                ('argument_score_con', models.FloatField()),
                ('rebuttal_score_con', models.FloatField()),
                ('clarity_score_con', models.FloatField()),
                ('persuasion_score_con', models.FloatField()),
                ('reasoning', models.TextField()),
                ('strongest_moment', models.TextField()),
                ('coaching_tip_pro', models.TextField()),
                ('coaching_tip_con', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('debate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='debate.debate')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judged_wins', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_type', models.CharField(choices=[('OPENING', 'Opening'), ('REBUTTAL', 'Rebuttal'), ('CLOSING', 'Closing')], max_length=20)),
                ('order', models.IntegerField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('debate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='debate.debate')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('debate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='debate.debate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='debate.round')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debate.category')),
            ],
        ),
        migrations.CreateModel(
            name='MatchQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_or_con', models.CharField(choices=[('PRO', 'Pro'), ('CON', 'Con')], max_length=20)),
                ('matched', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('MATCHED', 'Matched'), ('CANCELLED', 'Cancelled'), ('ABANDONED', 'Abandoned')], max_length=20)),
                ('matched_at', models.DateTimeField(blank=True, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('debate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='debate.debate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debate.topic')),
            ],
        ),
        migrations.AddField(
            model_name='debate',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debate.topic'),
        ),
    ]
