# Generated by Django 6.0.4 on 2026-05-04 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='category_backgrounds/'),
        ),
        migrations.AddField(
            model_name='topic',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='topic_backgrounds/'),
        ),
        migrations.AddField(
            model_name='topic',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
