# Generated by Django 6.0.4 on 2026-04-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchqueue',
            name='pro_or_con',
            field=models.CharField(choices=[('PRO', 'Pro'), ('CON', 'Con')], default='pro', max_length=20),
            preserve_default=False,
        ),
    ]
