# Generated by Django 6.0.4 on 2026-05-11 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0003_round_current_speaker_round_turn_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='category_icon/'),
        ),
        migrations.AddField(
            model_name='topic',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='topic_icon/'),
        ),
    ]
