# Generated by Django 6.0.4 on 2026-06-20 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0004_category_icon_topic_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='judgement',
            name='overall_score_con',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='judgement',
            name='overall_score_pro',
            field=models.FloatField(default=0),
        ),
    ]
